### ISSUE TITLE
other ways of accessing data

### ISSUE THREAD

**Issue by singha53-zz** [phuse-org/PODR#1]
Hello,

Is it possible to access PODR using anything other than powerbi or tableau? e.g. postman?
A

**Comment by nihpo** [comment]
Hello, thank you for your question.

Yes, you can access PODR from any tool that connects to a PostgreSQL database.

If you go to https://github.com/phuse-org/PODR/tree/master/sample_code
you'll find sample code in both Java and Python.

Please send me an email and I'll set you up with a username and passwords to connect to PODR:
Jose.Lacal@phuse.eu

Thank you for your interest in PODR. Regards.
